/**
 * Mapeamento exaustivo: cada medida do PETS → dataset(s) da API → parâmetros de query.
 * Quando não existe dataset API, usa-se source: 'static'.
 */

export type DataSource = 'sns_transparencia' | 'dados_gov' | 'static';
export type Prioridade = 'urgente' | 'prioritaria' | 'estruturante';

export interface Indicator {
  id: string;              // ex: 'E1.A1'
  eixo: 1 | 2 | 3 | 4 | 5;
  prioridade: Prioridade;
  nome: string;
  descricao: string;
  source: DataSource;
  dataset?: string;        // slug do dataset (se source != 'static')
  queryParams?: Record<string, string>; // filtros específicos
  decomposicaoULS: boolean;
  indicadores: string[];   // nomes dos campos/métricas a extrair
}

export const INDICATORS: Indicator[] = [
  // ═══════════════════════════════════════════
  // EIXO 1 — RESPOSTA A TEMPO E HORAS
  // ═══════════════════════════════════════════

  {
    id: 'E1.A1',
    eixo: 1,
    prioridade: 'urgente',
    nome: 'Regularização da lista de espera para cirurgia oncológica (OncoStop2024)',
    descricao: 'Programa cirúrgico extraordinário para doentes oncológicos fora do TMRG',
    source: 'sns_transparencia',
    dataset: 'atividade-cirurgica-programada',
    queryParams: { where: "tipo_patologia = 'Oncológica'" },
    decomposicaoULS: true,
    indicadores: ['doentes_operados', 'doentes_fora_tmrg', 'tempo_medio_espera'],
  },
  {
    id: 'E1.A2',
    eixo: 1,
    prioridade: 'urgente',
    nome: 'Aproximação do SNS ao cidadão através da Linha SNS24',
    descricao: 'Envolvimento do SNS24 no agendamento e comunicação com doentes em LIC',
    source: 'sns_transparencia',
    dataset: 'atividade-assistencial-sns-24',
    decomposicaoULS: false,
    indicadores: ['chamadas_realizadas', 'agendamentos', 'encaminhamentos'],
  },
  {
    id: 'E1.B1',
    eixo: 1,
    prioridade: 'prioritaria',
    nome: 'Programa cirúrgico para doentes não-oncológicos',
    descricao: 'Redução da LIC acima do TMRG para doentes não oncológicos',
    source: 'sns_transparencia',
    dataset: 'atividade-cirurgica-programada',
    queryParams: { where: "tipo_patologia != 'Oncológica'" },
    decomposicaoULS: true,
    indicadores: ['doentes_operados', 'doentes_fora_tmrg', 'variacao_homologa'],
  },
  {
    id: 'E1.B2',
    eixo: 1,
    prioridade: 'prioritaria',
    nome: 'Nova prioridade clínica para doentes oncológicos',
    descricao: 'Revisão regulamentar dos indicadores oncológicos e TMRG',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_legislacao'],
  },
  {
    id: 'E1.B3',
    eixo: 1,
    prioridade: 'prioritaria',
    nome: 'Reforço do acesso à consulta especializada',
    descricao: 'Redução das LEC fora do TMRG, aumento de primeiras consultas CTH',
    source: 'sns_transparencia',
    dataset: 'primeiras-consultas-hospitalares-realizadas',
    decomposicaoULS: true,
    indicadores: ['primeiras_consultas', 'consultas_subsequentes', 'percentagem_tmrg'],
  },
  {
    id: 'E1.C1',
    eixo: 1,
    prioridade: 'estruturante',
    nome: 'Monitorização à distância do doente crónico',
    descricao: 'Programa de teleconsulta e devices para doentes crónicos',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E1.C2',
    eixo: 1,
    prioridade: 'estruturante',
    nome: 'Revisão de protocolos para consulta de especialidade nos CSP',
    descricao: 'Revisão dos protocolos de referenciação CSP → Hospital',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E1.C3',
    eixo: 1,
    prioridade: 'estruturante',
    nome: 'Alargamento da Hospitalização Domiciliária',
    descricao: 'Expansão da HD para doentes pós-operatórios',
    source: 'sns_transparencia',
    dataset: 'hospitalizacao-domiciliaria',
    decomposicaoULS: true,
    indicadores: ['episodios_hd', 'doentes_acompanhados'],
  },
  {
    id: 'E1.C4',
    eixo: 1,
    prioridade: 'estruturante',
    nome: 'Revisão dos protocolos para inclusão de doente em LIC',
    descricao: 'Esgotar alternativas terapêuticas antes de inscrição na LIC',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E1.C5',
    eixo: 1,
    prioridade: 'estruturante',
    nome: 'Monitorização de acompanhamento à atividade adicional',
    descricao: 'Regulamentação de monitorização e fiscalização do cumprimento dos TMRG',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },

  // ═══════════════════════════════════════════
  // EIXO 2 — BEBÉS E MÃES EM SEGURANÇA
  // ═══════════════════════════════════════════

  {
    id: 'E2.A1',
    eixo: 2,
    prioridade: 'urgente',
    nome: 'Criação de canal de atendimento direto para a grávida (SNS Grávida)',
    descricao: 'Linha telefónica diferenciada para grávidas via SNS24',
    source: 'sns_transparencia',
    dataset: 'atividade-assistencial-sns-24',
    queryParams: { where: "servico = 'SNS Grávida'" },
    decomposicaoULS: false,
    indicadores: ['triagens', 'encaminhamento_urgencia', 'encaminhamento_csp', 'autocuidados'],
  },
  {
    id: 'E2.A2',
    eixo: 2,
    prioridade: 'urgente',
    nome: 'Atribuição de incentivos financeiros para aumentar a capacidade de realização de partos',
    descricao: 'Incentivo por parto acima da produção média diária',
    source: 'sns_transparencia',
    dataset: 'partos-e-cesarianas-nos-cuidados-de-saude-hospitalares',
    decomposicaoULS: true,
    indicadores: ['partos_total', 'taxa_cesarianas', 'partos_por_regiao'],
  },
  {
    id: 'E2.A3',
    eixo: 2,
    prioridade: 'urgente',
    nome: 'Reforço de convenções com o setor social e privado',
    descricao: 'Protocolo com setor privado para partos, especialmente em LVT',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['partos_protocolo_privado'],
  },
  {
    id: 'E2.B1',
    eixo: 2,
    prioridade: 'prioritaria',
    nome: 'Criação de regime de Atendimento Referenciado de Ginecologia de Urgência (ARGU)',
    descricao: 'Consulta aberta de ginecologia para libertar urgências de obstetrícia',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['uls_com_argu'],
  },
  {
    id: 'E2.B2',
    eixo: 2,
    prioridade: 'prioritaria',
    nome: 'Atualização dos rácios de pessoal e composição das equipas nos locais de parto',
    descricao: 'Clarificação de rácios de pessoal para funcionamento por capacidade diária',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E2.B3',
    eixo: 2,
    prioridade: 'prioritaria',
    nome: 'Revisão da tabela de preços convencionados para MCDT (ecografias pré-natais)',
    descricao: 'Atualização dos preços de ecografias obstétricas no setor convencionado',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['preco_1trimestre', 'preco_2trimestre', 'preco_3trimestre'],
  },
  {
    id: 'E2.B4',
    eixo: 2,
    prioridade: 'prioritaria',
    nome: 'Generalização do Atendimento Pediátrico Referenciado (APR)',
    descricao: 'Consultas abertas de pediatria para azuis e verdes da triagem Manchester',
    source: 'sns_transparencia',
    dataset: 'atendimentos-em-urgencia',
    queryParams: { where: "especialidade = 'Pediatria'" },
    decomposicaoULS: true,
    indicadores: ['atendimentos_azul_verde', 'atendimentos_total'],
  },
  {
    id: 'E2.C1',
    eixo: 2,
    prioridade: 'estruturante',
    nome: 'Separação das especialidades de Ginecologia e Obstetrícia',
    descricao: 'Segmentação das especialidades para maior foco e especialização',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E2.C2',
    eixo: 2,
    prioridade: 'estruturante',
    nome: 'Reforço do acompanhamento da grávida por EESMO',
    descricao: 'Acompanhamento contínuo por Especialistas de Enfermagem Materna e Obstétrica',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E2.C3',
    eixo: 2,
    prioridade: 'estruturante',
    nome: 'Estabelecimento de novas estruturas organizacionais para blocos de parto',
    descricao: 'Modelo de organização com maior autonomia para blocos de parto/obstetrícia',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },

  // ═══════════════════════════════════════════
  // EIXO 3 — CUIDADOS URGENTES E EMERGENTES
  // ═══════════════════════════════════════════

  {
    id: 'E3.A1',
    eixo: 3,
    prioridade: 'urgente',
    nome: 'Requalificação dos espaços dos Serviços de Urgência',
    descricao: 'Obras em urgências gerais e psiquiátricas, financiamento de 40M€',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['requalificacoes_em_curso', 'taxa_execucao_financeira'],
  },
  {
    id: 'E3.A2',
    eixo: 3,
    prioridade: 'urgente',
    nome: 'Criação de Centros de Atendimento Clínico (CAC)',
    descricao: 'Atendimento de situações agudas de menor complexidade fora do SU',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['num_cac_operacionais', 'atendimentos_total', 'referenciados_sns24'],
  },
  {
    id: 'E3.A3',
    eixo: 3,
    prioridade: 'urgente',
    nome: 'Implementação da consulta do dia seguinte nos CSP',
    descricao: 'Agendamento para CSP de utentes azuis/verdes da urgência ou SNS24',
    source: 'sns_transparencia',
    dataset: 'consultas-nos-cuidados-de-saude-primarios',
    decomposicaoULS: true,
    indicadores: ['agendamentos_dia_seguinte', 'consultas_realizadas'],
  },
  {
    id: 'E3.B1',
    eixo: 3,
    prioridade: 'prioritaria',
    nome: 'Libertação de camas indevidamente ocupadas nos internamentos hospitalares',
    descricao: 'Retirar situações sociais de camas de agudos',
    source: 'sns_transparencia',
    dataset: 'lotacao-praticada-por-tipo-de-cama',
    decomposicaoULS: true,
    indicadores: ['lotacao_praticada', 'camas_disponiveis', 'taxa_ocupacao'],
  },
  {
    id: 'E3.B2',
    eixo: 3,
    prioridade: 'prioritaria',
    nome: 'Criação da especialidade médica de Urgência',
    descricao: 'Aprovação e regulamentação da especialidade de Medicina de Urgência',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_legislacao', 'vagas_internato'],
  },
  {
    id: 'E3.B3',
    eixo: 3,
    prioridade: 'prioritaria',
    nome: 'Desenvolvimento de programas de vacinação contra Gripe e VSR',
    descricao: 'Campanhas de vacinação sazonal para populações vulneráveis',
    source: 'sns_transparencia',
    dataset: 'vacinas-contra-a-gripe',
    decomposicaoULS: false,
    indicadores: ['doses_administradas', 'taxa_cobertura'],
  },
  {
    id: 'E3.B4',
    eixo: 3,
    prioridade: 'prioritaria',
    nome: 'Realização de teleconsultas médicas em situações de menor complexidade',
    descricao: 'Teleconsulta via SNS24 para utentes não urgentes',
    source: 'sns_transparencia',
    dataset: 'consultas-nos-cuidados-de-saude-primarios',
    queryParams: { where: "tipo_consulta = 'Teleconsulta'" },
    decomposicaoULS: true,
    indicadores: ['teleconsultas_realizadas'],
  },
  {
    id: 'E3.B5',
    eixo: 3,
    prioridade: 'prioritaria',
    nome: 'Desenvolvimento do algoritmo do SNS24 para pré-triagem',
    descricao: 'Melhorias no encaminhamento, referenciação e agendamento pelo SNS24',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E3.B6',
    eixo: 3,
    prioridade: 'prioritaria',
    nome: 'Realização de campanhas de informação via farmácias comunitárias',
    descricao: 'Campanhas sobre uso correto dos serviços de saúde nas farmácias',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['num_farmacias_aderentes', 'campanhas_realizadas'],
  },
  {
    id: 'E3.B7',
    eixo: 3,
    prioridade: 'prioritaria',
    nome: 'Criação do Departamento de Urgência e Emergência Médica na DE-SNS',
    descricao: 'Unidade centralizada para gestão da rede de urgência e emergência',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_legislacao'],
  },
  {
    id: 'E3.B8',
    eixo: 3,
    prioridade: 'prioritaria',
    nome: 'Transporte inter-hospitalar integrado do doente crítico',
    descricao: 'Ambulâncias INEM dedicadas ao transporte crítico em Lisboa, Porto e Coimbra',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_legislacao', 'transportes_realizados'],
  },
  {
    id: 'E3.C1',
    eixo: 3,
    prioridade: 'estruturante',
    nome: 'Alteração do modelo dos locais de atendimento de doentes de menor complexidade',
    descricao: 'Substituição do modelo SASU pelo Centro de Atendimento Clínico',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E3.C2',
    eixo: 3,
    prioridade: 'estruturante',
    nome: 'Apoio médico a doentes em lares (ERPI)',
    descricao: 'Deslocação de médicos USF a ERPI para reduzir idas desnecessárias ao SU',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },

  // ═══════════════════════════════════════════
  // EIXO 4 — SAÚDE PRÓXIMA E FAMILIAR
  // ═══════════════════════════════════════════

  {
    id: 'E4.A1',
    eixo: 4,
    prioridade: 'urgente',
    nome: 'Atribuição de Médicos de Família aos utentes em espera',
    descricao: 'Otimização da atribuição de MdF com critérios de estratificação de risco',
    source: 'sns_transparencia',
    dataset: 'utentes-inscritos-em-cuidados-de-saude-primarios',
    decomposicaoULS: true,
    indicadores: ['utentes_sem_mdf', 'utentes_com_mdf', 'num_medicos_familia', 'percentagem_sem_mdf'],
  },
  {
    id: 'E4.A2',
    eixo: 4,
    prioridade: 'urgente',
    nome: 'Reforço da resposta pública dos CSP em parceria com o setor social (Batas Brancas)',
    descricao: 'Protocolo com Misericórdias e Cruz Vermelha para médico assistente',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['consultas_acumuladas', 'uls_participantes', 'instituicoes_sociais'],
  },
  {
    id: 'E4.A3',
    eixo: 4,
    prioridade: 'urgente',
    nome: 'Estabelecimento da PPP com Hospital de Cascais',
    descricao: 'Capacidade adicional de CSP em Cascais e Sintra para 75.000 utentes',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_legislacao', 'utentes_cobertos'],
  },
  {
    id: 'E4.A4',
    eixo: 4,
    prioridade: 'urgente',
    nome: 'Criação de linha de atendimento para acesso a médico no dia',
    descricao: 'Canal "Ligue antes, salve vidas" para atribuição de médico assistente',
    source: 'sns_transparencia',
    dataset: 'atividade-assistencial-sns-24',
    decomposicaoULS: false,
    indicadores: ['chamadas_atendidas', 'tempo_medio_espera'],
  },
  {
    id: 'E4.B1',
    eixo: 4,
    prioridade: 'prioritaria',
    nome: 'Implementação de USF-modelo C',
    descricao: 'Concurso público para agrupamentos de USF-C em LVT, Algarve e Leiria',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['candidaturas', 'utentes_estimados', 'estado_legislacao'],
  },
  {
    id: 'E4.B2',
    eixo: 4,
    prioridade: 'prioritaria',
    nome: 'Reforço da resposta pública com médicos aposentados',
    descricao: 'Prorrogação e revisão do regime de contratação de médicos aposentados',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['medicos_contratados', 'vagas_autorizadas'],
  },
  {
    id: 'E4.B3',
    eixo: 4,
    prioridade: 'prioritaria',
    nome: 'Revisão dos critérios de transição de USF-A e UCSP para USF-B',
    descricao: 'Redução do limiar IDG e adaptação a regiões de baixa densidade',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_legislacao', 'novas_usf_b'],
  },
  {
    id: 'E4.B4',
    eixo: 4,
    prioridade: 'prioritaria',
    nome: 'Reforço da resposta pública em parceria com setor privado',
    descricao: 'Convenções com associações de médicos e cooperativas',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E4.B5',
    eixo: 4,
    prioridade: 'prioritaria',
    nome: 'Incentivo à adesão ao regime voluntário de carteira adicional de utentes',
    descricao: 'Regime voluntário para médicos adicionarem até 200 utentes',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E4.C1',
    eixo: 4,
    prioridade: 'estruturante',
    nome: 'Disponibilização de MCDT em química seca e radiologia convencional',
    descricao: 'Dotar CSP de meios de diagnóstico rápido em zonas remotas',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },
  {
    id: 'E4.C2',
    eixo: 4,
    prioridade: 'estruturante',
    nome: 'Dinamização de rastreios oncológicos nos CSP',
    descricao: 'Expansão dos rastreios mama, colo do útero e colorretal',
    source: 'sns_transparencia',
    dataset: 'rastreios-oncologicos',
    decomposicaoULS: true,
    indicadores: ['cobertura_mama', 'cobertura_colo', 'cobertura_colorretal'],
  },
  {
    id: 'E4.C3',
    eixo: 4,
    prioridade: 'estruturante',
    nome: 'Criação de Centros de Avaliação Médica e Psicológica (CAMP)',
    descricao: 'Centralização da emissão de atestados para libertar tempo médico',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_implementacao'],
  },

  // ═══════════════════════════════════════════
  // EIXO 5 — SAÚDE MENTAL
  // ═══════════════════════════════════════════

  {
    id: 'E5.A1',
    eixo: 5,
    prioridade: 'urgente',
    nome: 'Contratação de psicólogos para os CSP',
    descricao: 'Reforço de 100 psicólogos nos Cuidados de Saúde Primários',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['psicologos_contratados', 'total_sns', 'vagas_em_concurso'],
  },
  {
    id: 'E5.A2',
    eixo: 5,
    prioridade: 'urgente',
    nome: 'Programa estruturado de Saúde Mental para forças de segurança (PSP e GNR)',
    descricao: 'Via Verde e equipas multidisciplinares dedicadas nos CSP',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_legislacao'],
  },
  {
    id: 'E5.A3',
    eixo: 5,
    prioridade: 'urgente',
    nome: 'Desinstitucionalização de situações crónicas em saúde mental',
    descricao: 'Criação de 500 respostas residenciais comunitárias',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['respostas_criadas', 'candidaturas'],
  },
  {
    id: 'E5.B1',
    eixo: 5,
    prioridade: 'prioritaria',
    nome: 'Criação de Equipas Comunitárias de Saúde Mental (ECSM)',
    descricao: '40 ECSM multidisciplinares para adultos, infância e adolescência',
    source: 'static',
    decomposicaoULS: true,
    indicadores: ['ecsm_criadas', 'ecsm_operacionais'],
  },
  {
    id: 'E5.B2',
    eixo: 5,
    prioridade: 'prioritaria',
    nome: 'Programas de intervenção na ansiedade e depressão nos CSP',
    descricao: '5 programas-piloto de intervenção não farmacológica',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['programas_piloto', 'estado_implementacao'],
  },
  {
    id: 'E5.B3',
    eixo: 5,
    prioridade: 'prioritaria',
    nome: 'Garantia da capacidade de internamento para situações agudas nos SLSM',
    descricao: 'Instalação de unidades de internamento psiquiátrico em hospitais gerais',
    source: 'sns_transparencia',
    dataset: 'lotacao-praticada-por-tipo-de-cama',
    queryParams: { where: "especialidade = 'Psiquiatria'" },
    decomposicaoULS: true,
    indicadores: ['camas_psiquiatria', 'taxa_ocupacao'],
  },
  {
    id: 'E5.B4',
    eixo: 5,
    prioridade: 'prioritaria',
    nome: 'Criação de serviços de saúde mental regionais para doentes de elevada complexidade',
    descricao: 'Reorganização de Magalhães Lemos, Sobral Cid e Júlio de Matos',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['obras_concluidas', 'obras_em_curso'],
  },
  {
    id: 'E5.C1',
    eixo: 5,
    prioridade: 'estruturante',
    nome: 'Construção dos serviços forenses no Hospital Sobral Cid e Júlio de Matos',
    descricao: 'Dois novos serviços forenses (40 camas cada), financiados pelo PRR',
    source: 'static',
    decomposicaoULS: false,
    indicadores: ['estado_construcao'],
  },
  {
    id: 'E5.C2',
    eixo: 5,
    prioridade: 'estruturante',
    nome: 'Generalização dos CRI em todos os Serviços Locais de Saúde Mental',
    descricao: '15 projetos-piloto CRI em funcionamento desde julho 2024',
    source: 'static',
    decomposicaoULS: true,
    indicadores: ['cri_operacionais', 'cri_previstos'],
  },
];

// Helper: obter indicadores por eixo
export function getIndicatorsByEixo(eixo: number): Indicator[] {
  return INDICATORS.filter(i => i.eixo === eixo);
}

// Helper: obter indicadores que usam API (não estáticos)
export function getAPIIndicators(): Indicator[] {
  return INDICATORS.filter(i => i.source !== 'static');
}

// Helper: obter datasets únicos necessários
export function getUniqueDatasets(): string[] {
  return [...new Set(INDICATORS.filter(i => i.dataset).map(i => i.dataset!))];
}
