/**
 * Methodology analysis for all 54 PETS measures.
 * Grau 1-10 based on ability to independently verify using open data.
 */

export interface MeasureMethodology {
  medidaId: string;
  medidaNome: string;
  eixo: number;
  grau: number;
  justificacao: string;
  datasetsAbertos: string[];
  matchType: 'directo' | 'proxy' | 'parcial' | 'nenhum';
  limitacoes: string[];
  recomendacoes: string[];
}

export const MEASURE_METHODOLOGIES: MeasureMethodology[] = [
  // ═══ EIXO 1 ═══
  { medidaId: 'E1.A1', medidaNome: 'OncoStop2024', eixo: 1, grau: 4,
    justificacao: 'Dataset LIC disponivel mas sem discriminacao por patologia oncologica. O indicador-chave (doentes onco fora TMRG) nao e replicavel com dados abertos.',
    datasetsAbertos: ['inscritos-em-lic-dentro-do-tmrg-180-dias'], matchType: 'parcial',
    limitacoes: ['Sem decomposicao por patologia oncologica', 'Valor exacto do relatorio nao replicavel'],
    recomendacoes: ['Publicar LIC com decomposicao por patologia'] },
  { medidaId: 'E1.A2', medidaNome: 'SNS24 Cidadao', eixo: 1, grau: 5,
    justificacao: 'Dataset SNS24 disponivel com chamadas atendidas/recebidas mensal, mas sem decomposicao por motivo (contacto LIC vs. outros).',
    datasetsAbertos: ['atividade-operacional-do-sns-24'], matchType: 'parcial',
    limitacoes: ['Sem filtro por tipo de contacto (SMS LIC)'], recomendacoes: ['Publicar dados de contactos por tipo'] },
  { medidaId: 'E1.B1', medidaNome: 'Cirurgia Nao-Oncologica', eixo: 1, grau: 7,
    justificacao: 'Dataset intervencoes-cirurgicas com serie mensal longa, decomposicao por ULS e tipo. Verificacao independente do volume cirurgico possivel.',
    datasetsAbertos: ['intervencoes-cirurgicas', 'inscritos-em-lic-dentro-do-tmrg-180-dias'], matchType: 'directo',
    limitacoes: ['Dados cumulativos YTD requerem decumulacao'], recomendacoes: [] },
  { medidaId: 'E1.B2', medidaNome: 'Prioridade Oncologica', eixo: 1, grau: 2,
    justificacao: 'Medida legislativa sem indicador quantitativo nos dados abertos. Estado depende de publicacao em Diario da Republica.',
    datasetsAbertos: [], matchType: 'nenhum',
    limitacoes: ['Medida regulamentar, nao quantificavel com dados operacionais'], recomendacoes: ['Publicar estado de processos legislativos em formato aberto'] },
  { medidaId: 'E1.B3', medidaNome: 'Consulta Especialidade', eixo: 1, grau: 8,
    justificacao: 'Dataset consultas-em-tempo-real com serie mensal, decomposicao ULS, % dentro TMRG. Verificacao independente forte.',
    datasetsAbertos: ['consultas-em-tempo-real'], matchType: 'directo',
    limitacoes: ['Dados cumulativos YTD'], recomendacoes: [] },
  { medidaId: 'E1.C1', medidaNome: 'Teleconsulta Cronicos', eixo: 1, grau: 5,
    justificacao: 'Dataset teleconsultas existe mas sem decomposicao por tipo de doente (cronico vs. agudo).',
    datasetsAbertos: ['teleconsultas-atraves-da-plataforma-live'], matchType: 'proxy',
    limitacoes: ['Sem filtro por tipo de doente'], recomendacoes: ['Decomposicao por tipo'] },
  { medidaId: 'E1.C2', medidaNome: 'Protocolos CSP-Hospital', eixo: 1, grau: 1,
    justificacao: 'Medida organizacional sem dados abertos. Estado depende de informacao interna do SNS.',
    datasetsAbertos: [], matchType: 'nenhum',
    limitacoes: ['Nenhum dataset disponivel'], recomendacoes: ['Publicar n.o de protocolos revistos'] },
  { medidaId: 'E1.C3', medidaNome: 'Hospitalizacao Domiciliaria', eixo: 1, grau: 2,
    justificacao: 'Nenhum dataset publico de hospitalizacao domiciliaria encontrado nos portais.',
    datasetsAbertos: [], matchType: 'nenhum',
    limitacoes: ['Dataset nao existe nos portais publicos'], recomendacoes: ['Publicar dados de HD por ULS'] },
  { medidaId: 'E1.C4', medidaNome: 'Protocolos LIC', eixo: 1, grau: 6,
    justificacao: 'Dataset LIC disponivel com total inscritos e % dentro TMRG. Proxy aceitavel para monitorizacao da medida.',
    datasetsAbertos: ['inscritos-em-lic-dentro-do-tmrg-180-dias'], matchType: 'proxy',
    limitacoes: ['Nao mede directamente revisao de protocolos'], recomendacoes: [] },
  { medidaId: 'E1.C5', medidaNome: 'Monitorizacao TMRG', eixo: 1, grau: 1,
    justificacao: 'Medida regulamentar sem indicador quantificavel nos dados abertos.',
    datasetsAbertos: [], matchType: 'nenhum',
    limitacoes: ['Medida regulamentar'], recomendacoes: ['Publicar indicadores de fiscalizacao'] },

  // ═══ EIXO 2 ═══
  { medidaId: 'E2.A1', medidaNome: 'SNS Gravida', eixo: 2, grau: 5,
    justificacao: 'SNS24 tem dados de chamadas mas sem filtro por servico SNS Gravida.',
    datasetsAbertos: ['atividade-operacional-do-sns-24'], matchType: 'parcial',
    limitacoes: ['Sem decomposicao por servico'], recomendacoes: ['Publicar dados SNS Gravida separados'] },
  { medidaId: 'E2.A2', medidaNome: 'Incentivos Partos', eixo: 2, grau: 7,
    justificacao: 'Dataset partos-e-cesarianas com serie mensal longa, decomposicao ULS, partos e cesarianas.',
    datasetsAbertos: ['partos-e-cesarianas'], matchType: 'directo',
    limitacoes: ['Nao mede incentivos financeiros, apenas volume'], recomendacoes: [] },
  { medidaId: 'E2.A3', medidaNome: 'Convencoes Privado', eixo: 2, grau: 2,
    justificacao: 'Nenhum dataset publico sobre convencoes setor privado para partos.',
    datasetsAbertos: [], matchType: 'nenhum',
    limitacoes: ['Dados contratuais nao publicos'], recomendacoes: ['Publicar dados de convencoes'] },
  { medidaId: 'E2.B1', medidaNome: 'ARGU', eixo: 2, grau: 3,
    justificacao: 'Referencia nos relatorios sem dados abertos especificos.',
    datasetsAbertos: ['atendimentos-por-tipo-de-urgencia-hospitalar-link'], matchType: 'proxy',
    limitacoes: ['Sem campo especifico para ARGU'], recomendacoes: [] },
  { medidaId: 'E2.B2', medidaNome: 'Racios Pessoal', eixo: 2, grau: 3,
    justificacao: 'Dataset trabalhadores existe mas sem decomposicao por servico obstetrico.',
    datasetsAbertos: ['trabalhadores-por-grupo-profissional'], matchType: 'proxy',
    limitacoes: ['Sem decomposicao por servico'], recomendacoes: [] },
  { medidaId: 'E2.B3', medidaNome: 'Tabela Ecografias', eixo: 2, grau: 1,
    justificacao: 'Medida de actualizacao de tabela de precos. Sem dados abertos.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Medida regulamentar'], recomendacoes: [] },
  { medidaId: 'E2.B4', medidaNome: 'APR Pediatria', eixo: 2, grau: 6,
    justificacao: 'Dataset urgencias tem campo urgencias_pediatricas. Proxy para avaliar desvio.',
    datasetsAbertos: ['atendimentos-por-tipo-de-urgencia-hospitalar-link'], matchType: 'proxy',
    limitacoes: ['Nao distingue APR de urgencia normal'], recomendacoes: [] },
  { medidaId: 'E2.C1', medidaNome: 'Separacao Gineco/Obst.', eixo: 2, grau: 1,
    justificacao: 'Medida organizacional sem dados abertos.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Organizacional'], recomendacoes: [] },
  { medidaId: 'E2.C2', medidaNome: 'EESMO', eixo: 2, grau: 1,
    justificacao: 'Sem dados abertos sobre acompanhamento por EESMO.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados'], recomendacoes: [] },
  { medidaId: 'E2.C3', medidaNome: 'Blocos Parto', eixo: 2, grau: 1,
    justificacao: 'Medida organizacional sem dados abertos.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Organizacional'], recomendacoes: [] },

  // ═══ EIXO 3 ═══
  { medidaId: 'E3.A1', medidaNome: 'Requalificacao SU', eixo: 3, grau: 2,
    justificacao: 'Obras fisicas sem dados abertos de execucao.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados de execucao'], recomendacoes: ['Publicar execucao PRR'] },
  { medidaId: 'E3.A2', medidaNome: 'CAC', eixo: 3, grau: 3,
    justificacao: 'Dados de CAC existem apenas nos relatorios GT PETS. Sem dataset API.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dataset API para CAC'], recomendacoes: ['Publicar dados de CAC'] },
  { medidaId: 'E3.A3', medidaNome: 'Consulta Dia Seguinte', eixo: 3, grau: 5,
    justificacao: 'Dataset consultas CSP existe mas sem identificacao de consultas dia seguinte.',
    datasetsAbertos: ['consultas-em-tempo-real'], matchType: 'proxy',
    limitacoes: ['Sem campo dia seguinte'], recomendacoes: [] },
  { medidaId: 'E3.B1', medidaNome: 'Libertacao Camas', eixo: 3, grau: 7,
    justificacao: 'Dataset lotacao-praticada e ocupacao-internamento com serie mensal e ULS.',
    datasetsAbertos: ['lotacao-praticada-por-tipo-de-cama', 'ocupacao-do-internamento'], matchType: 'directo',
    limitacoes: ['Nao distingue camas contratadas vs. proprias'], recomendacoes: [] },
  { medidaId: 'E3.B2', medidaNome: 'Especialidade Urgencia', eixo: 3, grau: 2,
    justificacao: 'Medida regulamentar (aprovacao pela OM). Sem dados abertos.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Regulamentar'], recomendacoes: [] },
  { medidaId: 'E3.B3', medidaNome: 'Vacinacao Gripe/VSR', eixo: 3, grau: 5,
    justificacao: 'Dataset vacinacao gripe disponivel mas sem decomposicao por VSR.',
    datasetsAbertos: ['atendimentos-nos-csp-gripe'], matchType: 'parcial',
    limitacoes: ['Sem dados VSR'], recomendacoes: [] },
  { medidaId: 'E3.B4', medidaNome: 'Teleconsultas', eixo: 3, grau: 6,
    justificacao: 'Dataset teleconsultas disponivel com serie mensal.',
    datasetsAbertos: ['consultas-em-telemedicina'], matchType: 'directo',
    limitacoes: ['Sem decomposicao por complexidade'], recomendacoes: [] },
  { medidaId: 'E3.B5', medidaNome: 'Algoritmo SNS24', eixo: 3, grau: 2,
    justificacao: 'Desenvolvimento de software sem indicadores abertos.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Desenvolvimento SW'], recomendacoes: [] },
  { medidaId: 'E3.B6', medidaNome: 'Campanhas Farmacias', eixo: 3, grau: 1,
    justificacao: 'Sem dados abertos sobre campanhas em farmacias.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados'], recomendacoes: [] },
  { medidaId: 'E3.B7', medidaNome: 'Dept. Urgencia', eixo: 3, grau: 2,
    justificacao: 'Criacao organizacional. Verificavel via Diario da Republica mas sem dados operacionais.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Organizacional'], recomendacoes: [] },
  { medidaId: 'E3.B8', medidaNome: 'Transporte Critico', eixo: 3, grau: 2,
    justificacao: 'Medida regulamentar. Verificavel via legislacao mas sem dados de transporte.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Regulamentar'], recomendacoes: [] },
  { medidaId: 'E3.C1', medidaNome: 'Modelo CAC', eixo: 3, grau: 3,
    justificacao: 'Mesma situacao que E3.A2. Dados apenas nos relatorios.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dataset'], recomendacoes: [] },
  { medidaId: 'E3.C2', medidaNome: 'Apoio ERPI', eixo: 3, grau: 1,
    justificacao: 'Sem qualquer dado publico sobre apoio medico a lares.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados'], recomendacoes: ['Publicar dados apoio ERPI'] },

  // ═══ EIXO 4 ═══
  { medidaId: 'E4.A1', medidaNome: 'Medicos Familia', eixo: 4, grau: 8,
    justificacao: 'Dataset utentes-inscritos-csp com serie mensal longa, decomposicao ULS, utentes com/sem MdF. Verificacao forte.',
    datasetsAbertos: ['utentes-inscritos-em-cuidados-de-saude-primarios'], matchType: 'directo',
    limitacoes: ['Dados cumulativos'], recomendacoes: [] },
  { medidaId: 'E4.A2', medidaNome: 'Batas Brancas', eixo: 4, grau: 3,
    justificacao: 'Dados apenas nos relatorios GT PETS. Sem dataset API especifico.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dataset API'], recomendacoes: ['Publicar dados Batas Brancas'] },
  { medidaId: 'E4.A3', medidaNome: 'PPP Cascais', eixo: 4, grau: 2,
    justificacao: 'PPP contratual sem dados operacionais publicos.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Contratual'], recomendacoes: [] },
  { medidaId: 'E4.A4', medidaNome: 'Ligue Antes', eixo: 4, grau: 6,
    justificacao: 'SNS24 com dados mensais. Proxy para Ligue Antes.',
    datasetsAbertos: ['atividade-operacional-do-sns-24'], matchType: 'proxy',
    limitacoes: ['Sem filtro Ligue Antes especifico'], recomendacoes: [] },
  { medidaId: 'E4.B1', medidaNome: 'USF-C', eixo: 4, grau: 4,
    justificacao: 'Dataset unidades funcionais existe mas sem discriminacao USF-C.',
    datasetsAbertos: ['evolucao-do-numero-de-unidades-funcionais'], matchType: 'proxy',
    limitacoes: ['Sem discriminacao por tipo USF'], recomendacoes: ['Decompor por tipo A/B/C'] },
  { medidaId: 'E4.B2', medidaNome: 'Medicos Aposentados', eixo: 4, grau: 3,
    justificacao: 'Dataset trabalhadores existe mas sem identificacao de aposentados recontratados.',
    datasetsAbertos: ['trabalhadores-por-grupo-profissional'], matchType: 'proxy',
    limitacoes: ['Sem campo aposentados'], recomendacoes: [] },
  { medidaId: 'E4.B3', medidaNome: 'Transicao USF-B', eixo: 4, grau: 4,
    justificacao: 'Dataset unidades funcionais sem decomposicao USF-A/B/C.',
    datasetsAbertos: ['evolucao-do-numero-de-unidades-funcionais'], matchType: 'proxy',
    limitacoes: ['Sem tipo USF'], recomendacoes: [] },
  { medidaId: 'E4.B4', medidaNome: 'Cooperativas Medicas', eixo: 4, grau: 1,
    justificacao: 'Sem dados publicos sobre parcerias com cooperativas.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados'], recomendacoes: [] },
  { medidaId: 'E4.B5', medidaNome: 'Carteira Adicional', eixo: 4, grau: 1,
    justificacao: 'Proposta em analise. Sem dados operacionais.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Nao implementada'], recomendacoes: [] },
  { medidaId: 'E4.C1', medidaNome: 'MCDT nos CSP', eixo: 4, grau: 1,
    justificacao: 'Sem dados publicos sobre quimica seca e radiologia nos CSP.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados'], recomendacoes: [] },
  { medidaId: 'E4.C2', medidaNome: 'Rastreios Oncologicos', eixo: 4, grau: 8,
    justificacao: 'Dataset rastreios-oncologicos com 3 indicadores (mama, colo, colorretal), serie longa, decomposicao ULS.',
    datasetsAbertos: ['rastreios-oncologicos'], matchType: 'directo',
    limitacoes: ['Dados sao proporcoes, nao contagens absolutas'], recomendacoes: [] },
  { medidaId: 'E4.C3', medidaNome: 'CAMP', eixo: 4, grau: 1,
    justificacao: 'Sem dados publicos sobre Centros de Avaliacao Medica e Psicologica.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados'], recomendacoes: [] },

  // ═══ EIXO 5 ═══
  { medidaId: 'E5.A1', medidaNome: 'Psicologos CSP', eixo: 5, grau: 5,
    justificacao: 'Dataset trabalhadores existe mas sem decomposicao por grupo especifico (psicologos).',
    datasetsAbertos: ['trabalhadores-por-grupo-profissional'], matchType: 'proxy',
    limitacoes: ['Sem campo psicologos'], recomendacoes: ['Decompor por especialidade'] },
  { medidaId: 'E5.A2', medidaNome: 'SM Forcas Seguranca', eixo: 5, grau: 2,
    justificacao: 'Medida legislativa verificavel via Diario da Republica.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Regulamentar'], recomendacoes: [] },
  { medidaId: 'E5.A3', medidaNome: 'Desinstitucionalizacao', eixo: 5, grau: 2,
    justificacao: 'Aviso publicado mas sem dados operacionais de respostas criadas.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados operacionais'], recomendacoes: ['Publicar dados respostas residenciais'] },
  { medidaId: 'E5.B1', medidaNome: 'ECSM', eixo: 5, grau: 3,
    justificacao: 'Dados apenas nos relatorios GT PETS. 20 ECSM operacionais.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dataset'], recomendacoes: ['Publicar dados ECSM'] },
  { medidaId: 'E5.B2', medidaNome: 'Ansiedade/Depressao', eixo: 5, grau: 1,
    justificacao: 'Programas piloto nao iniciados. Sem dados.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Nao iniciado'], recomendacoes: [] },
  { medidaId: 'E5.B3', medidaNome: 'Internamento SLSM', eixo: 5, grau: 5,
    justificacao: 'Dataset lotacao-camas pode ser proxy para camas psiquiatria.',
    datasetsAbertos: ['lotacao-praticada-por-tipo-de-cama'], matchType: 'proxy',
    limitacoes: ['Sem filtro psiquiatria'], recomendacoes: [] },
  { medidaId: 'E5.B4', medidaNome: 'Servicos Regionais SM', eixo: 5, grau: 3,
    justificacao: 'Dados de obras apenas nos relatorios.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados'], recomendacoes: [] },
  { medidaId: 'E5.C1', medidaNome: 'Forenses', eixo: 5, grau: 3,
    justificacao: 'Dados de construcao apenas nos relatorios.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dados'], recomendacoes: [] },
  { medidaId: 'E5.C2', medidaNome: 'CRI', eixo: 5, grau: 3,
    justificacao: '15 CRI reportados nos relatorios. Sem dataset API.',
    datasetsAbertos: [], matchType: 'nenhum', limitacoes: ['Sem dataset'], recomendacoes: ['Publicar dados CRI'] },
];

// Stats
export const METHODOLOGY_STATS = {
  total: MEASURE_METHODOLOGIES.length,
  grauMedio: Math.round(MEASURE_METHODOLOGIES.reduce((s, m) => s + m.grau, 0) / MEASURE_METHODOLOGIES.length * 10) / 10,
  boaMonitorizacao: MEASURE_METHODOLOGIES.filter(m => m.grau >= 7).length,
  naoMonitorizavel: MEASURE_METHODOLOGIES.filter(m => m.grau <= 3).length,
  comDataset: MEASURE_METHODOLOGIES.filter(m => m.datasetsAbertos.length > 0).length,
};
